// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/CreateDigitalAssistant": {
            "post": {
                "description": "创建一个新的数字助手实例",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DigitalAssistant"
                ],
                "summary": "创建数字助手",
                "parameters": [
                    {
                        "description": "创建数字助手请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_contract.CreateDigitalAssistantRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.CreateDigitalAssistantResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未认证",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "内部服务器错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/DeleteDigitalAssistant": {
            "post": {
                "description": "根据ID删除数字助手",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DigitalAssistant"
                ],
                "summary": "删除数字助手",
                "parameters": [
                    {
                        "description": "删除数字助手请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/backend_internal_api_handler.DeleteDigitalAssistantRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.BaseResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未认证",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "权限不足",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "资源不存在",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "内部服务器错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/GetDigitalAssistant": {
            "post": {
                "description": "根据ID或Code获取数字助手详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DigitalAssistant"
                ],
                "summary": "获取数字助手详情",
                "parameters": [
                    {
                        "description": "获取数字助手请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/backend_internal_api_handler.GetDigitalAssistantRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.CreateDigitalAssistantResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未认证",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "权限不足",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "资源不存在",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "内部服务器错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ListDigitalAssistant": {
            "post": {
                "description": "分页查询数字助手列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DigitalAssistant"
                ],
                "summary": "查询数字助手列表",
                "parameters": [
                    {
                        "description": "查询列表请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_contract.ListDigitalAssistantRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.CreateDigitalAssistantResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未认证",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "内部服务器错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/UpdateDigitalAssistant": {
            "post": {
                "description": "更新数字助手基本信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DigitalAssistant"
                ],
                "summary": "更新数字助手",
                "parameters": [
                    {
                        "description": "更新数字助手请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/backend_internal_api_handler.UpdateDigitalAssistantRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.CreateDigitalAssistantResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未认证",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "权限不足",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "资源不存在",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "内部服务器错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/UpdateDigitalAssistantConfig": {
            "post": {
                "description": "更新数字助手的配置信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DigitalAssistant"
                ],
                "summary": "更新数字助手配置",
                "parameters": [
                    {
                        "description": "更新配置请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/backend_internal_api_handler.UpdateDigitalAssistantConfigRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.CreateDigitalAssistantResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未认证",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "权限不足",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "资源不存在",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "内部服务器错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/UpdateDigitalAssistantStatus": {
            "post": {
                "description": "更新数字助手的运行状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DigitalAssistant"
                ],
                "summary": "更新数字助手状态",
                "parameters": [
                    {
                        "description": "更新状态请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/backend_internal_api_handler.UpdateDigitalAssistantStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.BaseResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未认证",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "权限不足",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "资源不存在",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "内部服务器错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "backend_internal_api_handler.DeleteDigitalAssistantRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "backend_internal_api_handler.GetDigitalAssistantRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "backend_internal_api_handler.UpdateDigitalAssistantConfigRequest": {
            "type": "object",
            "required": [
                "config",
                "id"
            ],
            "properties": {
                "config": {
                    "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_contract.AssistantConfig"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "backend_internal_api_handler.UpdateDigitalAssistantRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "config": {
                    "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_contract.AssistantConfig"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "backend_internal_api_handler.UpdateDigitalAssistantStatusRequest": {
            "type": "object",
            "required": [
                "id",
                "status"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_insmtx_SingerOS_backend_internal_api_contract.AssistantConfig": {
            "type": "object",
            "properties": {
                "channels": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_contract.ChannelRef"
                    }
                },
                "knowledge": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_contract.KnowledgeRef"
                    }
                },
                "llm_config": {
                    "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_contract.LLMConfig"
                },
                "memory_config": {
                    "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_contract.MemoryConfig"
                },
                "policies_config": {
                    "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_contract.PolicyConfig"
                },
                "runtime_config": {
                    "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_contract.RuntimeConfig"
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_contract.SkillRef"
                    }
                }
            }
        },
        "github_com_insmtx_SingerOS_backend_internal_api_contract.ChannelRef": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_insmtx_SingerOS_backend_internal_api_contract.CreateDigitalAssistantRequest": {
            "type": "object",
            "required": [
                "code",
                "config",
                "name",
                "org_id",
                "owner_id"
            ],
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "config": {
                    "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_contract.AssistantConfig"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "org_id": {
                    "type": "integer"
                },
                "owner_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_insmtx_SingerOS_backend_internal_api_contract.DigitalAssistant": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "config": {
                    "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_contract.AssistantConfig"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "org_id": {
                    "type": "integer"
                },
                "owner_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "github_com_insmtx_SingerOS_backend_internal_api_contract.KnowledgeRef": {
            "type": "object",
            "properties": {
                "dataset_id": {
                    "type": "string"
                },
                "repo": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_insmtx_SingerOS_backend_internal_api_contract.LLMConfig": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_insmtx_SingerOS_backend_internal_api_contract.ListDigitalAssistantRequest": {
            "type": "object",
            "properties": {
                "keyword": {
                    "type": "string"
                },
                "org_id": {
                    "type": "integer"
                },
                "owner_id": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_insmtx_SingerOS_backend_internal_api_contract.MemoryConfig": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_insmtx_SingerOS_backend_internal_api_contract.PolicyConfig": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_insmtx_SingerOS_backend_internal_api_contract.RuntimeConfig": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_insmtx_SingerOS_backend_internal_api_contract.SkillRef": {
            "type": "object",
            "properties": {
                "skill_code": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "github_com_insmtx_SingerOS_backend_internal_api_dto.BaseResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_insmtx_SingerOS_backend_internal_api_dto.CreateDigitalAssistantResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/github_com_insmtx_SingerOS_backend_internal_api_contract.DigitalAssistant"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_insmtx_SingerOS_backend_internal_api_dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "details": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{"http", "https"},
	Title:            "SingerOS API",
	Description:      "SingerOS 数字助手平台 API，提供数字助手管理、技能调用、事件处理等功能",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
